### ISSUE TITLE
err 500 after entering a password in the pass protection field...

### ISSUE THREAD

**Issue by dgillier** [ploi/roadmap#227]
Add a password in the backoffice and now having err 500 on frontend...

Having an err 500 on backoffice when trying to removed the password...

**Comment by Cannonb4ll** [comment]
Please also provide the actual error log.

**Comment by dgillier** [comment]
```
023-04-28 11:19:05] Production.ERROR: Mix manifest not found at: /home/mkpeurope-yaije/roadmap.mkpeurope.org/public/mix-manifest.json (View: /home/mkpeurope-yaije/roadmap.mkpeurope.org/res$
[stacktrace]
#0 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(106): Illuminate\\View\\Engines\\CompilerEngine->handleViewExcep$
#1 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Livewire\\LivewireViewCompilerEngine->handleViewException()
#2 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#3 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#4 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#5 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\LivewireViewCompilerEngine->get()
#6 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#7 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#8 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#9 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#10 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(906): Illuminate\\Http\\Response->__construct()
#11 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(875): Illuminate\\Routing\\Router::toResponse()
#12 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Router->prepareResponse()
#13 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#14 /home/mkpeurope-yaije/roadmap.mkpeurope.org/app/Http/Middleware/LocalizeDates.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\LocalizeDates->handle()
#16 /home/mkpeurope-yaije/roadmap.mkpeurope.org/app/Http/Middleware/Localize.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Localize->handle()
#18 /home/mkpeurope-yaije/roadmap.mkpeurope.org/app/Http/Middleware/PasswordProtected.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\PasswordProtected->handle()
#20 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\$
#21 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#22 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipe$
#23 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#24 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline$
#25 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#26 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{clo$
#27 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatef$
#28 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#29 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pi$
#30 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{clo$
#32 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#35 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#36 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#37 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#38 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#39 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{clo$
#40 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#42 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pi$
#43 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middlewa$
#44 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->han$
#45 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pi$
#46 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\Transforms$
#47 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#48 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pip$
#49 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#50 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline-$
#51 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenan$
#52 /home/mkpeurope-yaije/roadmap.mkpeurope.org/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

```

**Comment by dgillier** [comment]
Looks like the mix manifest is not there , but I ran npm ci & npm run production...

**Comment by Cannonb4ll** [comment]
What's the output of the deployment and `npm ci && npm run production`?

**Comment by Cannonb4ll** [comment]
Closed due to inactivity.
